import "@/app/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { DM_Serif_Display } from "next/font/google";

const dmSerif = DM_Serif_Display({
  variable: "--font-header",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSerif.variable} antialiased`}>
        <Header />
        <div className="fixed inset-0 -z-10 h-full w-full bg-[url(/placeholder.jpg)] bg-cover bg-center bg-no-repeat"></div>
        <div className="w-full px-4 py-5">
          <main className="mt-20 bg-white min-h-screen shadow-xl rounded-t-lg max-w-[1200px] mx-auto px-5 lg:px-7 py-10">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
